export const PERMISSIONS = {
    VIEW_DASHBOARD: "VIEW_DASHBOARD",
    MANAGE_PRODUCTS: "MANAGE_PRODUCTS",
    MANAGE_ORDERS: "MANAGE_ORDERS",
    MANAGE_USERS: "MANAGE_USERS",
    VIEW_ANALYTICS: "VIEW_ANALYTICS",
    MANAGE_CATEGORY: "MANAGE_CATEGORY",
  } as const
  
  // ✅ INCLUDE "ALL" INSIDE TYPE
  export type Permission =
    | (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
    | "ALL"
  
  // ✅ ROLE PERMISSIONS
  export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
    ADMIN: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.MANAGE_PRODUCTS,
      PERMISSIONS.MANAGE_ORDERS,
      PERMISSIONS.VIEW_ANALYTICS,
    ],
  
    SUPER_ADMIN: ["ALL"],
  
    STAFF: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.MANAGE_ORDERS,
    ],
  }